IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE UPPER(TABLE_SCHEMA) = 'DBO' AND UPPER(TABLE_NAME) = 'LOGS')
BEGIN
	CREATE TABLE logs (
	    id INT IDENTITY PRIMARY KEY,
	    event_date DATETIME,
	    level VARCHAR(10),
	    logger VARCHAR(255),
	    message VARCHAR(MAX),
	    exception VARCHAR(MAX)
	);
END