IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE UPPER(TABLE_SCHEMA) = 'DBO' AND UPPER(TABLE_NAME) = 'CITIES')
BEGIN
	CREATE TABLE Cities (
	    Id INT PRIMARY KEY IDENTITY,
	    NameEnglish NVARCHAR(100) NOT NULL,
	    NameArabic NVARCHAR(100) NOT NULL,	    
	    Visible bit NOT NULL
	);
END